{% set name = "airflow-provider-great-expectations" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cde3485c071a4e973ee29657ef561ec83674d052288ab2bc0a18fbb7bfd91dfa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.1
    - great-expectations <1.0.0,>=0.15.34
    - sqlalchemy >=1.3.16

test:
  imports:
    - great_expectations_provider
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/astronomer/airflow-provider-great-expectations
  summary: An Apache Airflow provider for Great Expectations
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
    - rxm7706
